# Justfile for zelos-proto crate

default:
	@just --list

build:
	cargo build -p zelos-proto

check:
	cargo check -p zelos-proto --all-targets

fmt:
	just -f ../../Justfile fmt

clippy:
	cargo clippy -p zelos-proto --all-targets -- -D warnings

test:
	cargo test -p zelos-proto

# Proto build (uses build.rs)
proto-build:
	cargo build -p zelos-proto
