# Justfile for zelos-trace crate

default:
	@just --list

build:
	cargo build -p zelos-trace

check:
	cargo check -p zelos-trace --all-targets

fmt:
	just -f ../../Justfile fmt

clippy:
	cargo clippy -p zelos-trace --all-targets -- -D warnings

test:
	cargo test -p zelos-trace

bench:
	cargo bench -p zelos-trace
