# Justfile for zelos-trace crate

set shell := ["bash", "-cu"]

default:
	@just --list

build:
	cargo build -p zelos-trace

check:
	cargo check -p zelos-trace --all-targets

fmt:
	cargo fmt -p zelos-trace

clippy:
	cargo clippy -p zelos-trace --all-targets -- -D warnings

test:
	cargo test -p zelos-trace

bench:
	cargo bench -p zelos-trace
