# Justfile for zelos-trace-types crate

default:
	@just --list

build:
	cargo build -p zelos-trace-types

check:
	cargo check -p zelos-trace-types --all-targets

fmt:
	just -f ../../Justfile fmt

clippy:
	cargo clippy -p zelos-trace-types --all-targets -- -D warnings

test:
	cargo test -p zelos-trace-types

bench:
	cargo bench -p zelos-trace-types
