# Justfile for zelos-trace-types crate

set shell := ["bash", "-cu"]

default:
	@just --list

build:
	cargo build -p zelos-trace-types

check:
	cargo check -p zelos-trace-types --all-targets

fmt:
	cargo fmt -p zelos-trace-types

clippy:
	cargo clippy -p zelos-trace-types --all-targets -- -D warnings

test:
	cargo test -p zelos-trace-types

bench:
	cargo bench -p zelos-trace-types
