// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: zeloscloud/actions/actions.proto

package actions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteStatus int32

const (
	ExecuteStatus_PASS  ExecuteStatus = 0
	ExecuteStatus_FAIL  ExecuteStatus = 1
	ExecuteStatus_ERROR ExecuteStatus = 2
	ExecuteStatus_DONE  ExecuteStatus = 3 // Completed without pass/fail classification (default for plain return values)
)

// Enum value maps for ExecuteStatus.
var (
	ExecuteStatus_name = map[int32]string{
		0: "PASS",
		1: "FAIL",
		2: "ERROR",
		3: "DONE",
	}
	ExecuteStatus_value = map[string]int32{
		"PASS":  0,
		"FAIL":  1,
		"ERROR": 2,
		"DONE":  3,
	}
)

func (x ExecuteStatus) Enum() *ExecuteStatus {
	p := new(ExecuteStatus)
	*p = x
	return p
}

func (x ExecuteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zeloscloud_actions_actions_proto_enumTypes[0].Descriptor()
}

func (ExecuteStatus) Type() protoreflect.EnumType {
	return &file_zeloscloud_actions_actions_proto_enumTypes[0]
}

func (x ExecuteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteStatus.Descriptor instead.
func (ExecuteStatus) EnumDescriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{0}
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                               // Name of the action to execute
	Params        string                 `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`                               // JSON string input parameters
	TimeoutMs     *uint32                `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3,oneof" json:"timeout_ms,omitempty"` // Timeout in milliseconds; absent means use server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *ExecuteRequest) GetTimeoutMs() uint32 {
	if x != nil && x.TimeoutMs != nil {
		return *x.TimeoutMs
	}
	return 0
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                              // Name of the action executed
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                                              // JSON string result payload
	Status        *ExecuteStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=zeloscloud.actions.ExecuteStatus,oneof" json:"status,omitempty"` // Status of the execution; absent = DONE (backward compat with old SDKs)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecuteResponse) GetStatus() ExecuteStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ExecuteStatus_PASS
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{2}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []string               `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"` // List of supported actions, e.g. ["action", "namespace/action"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // arbitrary status JSON string of the service's status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type SchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                    // Name of the action to get the schema for
	CurrentValues string                 `protobuf:"bytes,2,opt,name=current_values,json=currentValues,proto3" json:"current_values,omitempty"` // Optional JSON string of current form data for dynamic choices
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRequest) Reset() {
	*x = SchemaRequest{}
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRequest) ProtoMessage() {}

func (x *SchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRequest.ProtoReflect.Descriptor instead.
func (*SchemaRequest) Descriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{6}
}

func (x *SchemaRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SchemaRequest) GetCurrentValues() string {
	if x != nil {
		return x.CurrentValues
	}
	return ""
}

type SchemaResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Action           string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                                      // Name of the action
	ActionSchema     string                 `protobuf:"bytes,2,opt,name=action_schema,json=actionSchema,proto3" json:"action_schema,omitempty"`                      // Action Schema as JSON string
	UiSchema         string                 `protobuf:"bytes,3,opt,name=ui_schema,json=uiSchema,proto3" json:"ui_schema,omitempty"`                                  // UI Schema as JSON string
	DefaultTimeoutMs *uint32                `protobuf:"varint,4,opt,name=default_timeout_ms,json=defaultTimeoutMs,proto3,oneof" json:"default_timeout_ms,omitempty"` // Action-defined default timeout in milliseconds
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SchemaResponse) Reset() {
	*x = SchemaResponse{}
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaResponse) ProtoMessage() {}

func (x *SchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaResponse.ProtoReflect.Descriptor instead.
func (*SchemaResponse) Descriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{7}
}

func (x *SchemaResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SchemaResponse) GetActionSchema() string {
	if x != nil {
		return x.ActionSchema
	}
	return ""
}

func (x *SchemaResponse) GetUiSchema() string {
	if x != nil {
		return x.UiSchema
	}
	return ""
}

func (x *SchemaResponse) GetDefaultTimeoutMs() uint32 {
	if x != nil && x.DefaultTimeoutMs != nil {
		return *x.DefaultTimeoutMs
	}
	return 0
}

type ActionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint64                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Name of the service
	// Types that are valid to be assigned to Msg:
	//
	//	*ActionsRequest_List
	//	*ActionsRequest_Execute
	//	*ActionsRequest_Status
	//	*ActionsRequest_Schema
	Msg           isActionsRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionsRequest) Reset() {
	*x = ActionsRequest{}
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsRequest) ProtoMessage() {}

func (x *ActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsRequest.ProtoReflect.Descriptor instead.
func (*ActionsRequest) Descriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{8}
}

func (x *ActionsRequest) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ActionsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionsRequest) GetMsg() isActionsRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ActionsRequest) GetList() *ListResponse {
	if x != nil {
		if x, ok := x.Msg.(*ActionsRequest_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *ActionsRequest) GetExecute() *ExecuteResponse {
	if x != nil {
		if x, ok := x.Msg.(*ActionsRequest_Execute); ok {
			return x.Execute
		}
	}
	return nil
}

func (x *ActionsRequest) GetStatus() *StatusResponse {
	if x != nil {
		if x, ok := x.Msg.(*ActionsRequest_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ActionsRequest) GetSchema() *SchemaResponse {
	if x != nil {
		if x, ok := x.Msg.(*ActionsRequest_Schema); ok {
			return x.Schema
		}
	}
	return nil
}

type isActionsRequest_Msg interface {
	isActionsRequest_Msg()
}

type ActionsRequest_List struct {
	List *ListResponse `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

type ActionsRequest_Execute struct {
	Execute *ExecuteResponse `protobuf:"bytes,4,opt,name=execute,proto3,oneof"`
}

type ActionsRequest_Status struct {
	Status *StatusResponse `protobuf:"bytes,5,opt,name=status,proto3,oneof"`
}

type ActionsRequest_Schema struct {
	Schema *SchemaResponse `protobuf:"bytes,6,opt,name=schema,proto3,oneof"`
}

func (*ActionsRequest_List) isActionsRequest_Msg() {}

func (*ActionsRequest_Execute) isActionsRequest_Msg() {}

func (*ActionsRequest_Status) isActionsRequest_Msg() {}

func (*ActionsRequest_Schema) isActionsRequest_Msg() {}

type ActionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint64                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ActionsResponse_List
	//	*ActionsResponse_Execute
	//	*ActionsResponse_Status
	//	*ActionsResponse_Schema
	Msg           isActionsResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionsResponse) Reset() {
	*x = ActionsResponse{}
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsResponse) ProtoMessage() {}

func (x *ActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_actions_actions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsResponse.ProtoReflect.Descriptor instead.
func (*ActionsResponse) Descriptor() ([]byte, []int) {
	return file_zeloscloud_actions_actions_proto_rawDescGZIP(), []int{9}
}

func (x *ActionsResponse) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ActionsResponse) GetMsg() isActionsResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ActionsResponse) GetList() *ListRequest {
	if x != nil {
		if x, ok := x.Msg.(*ActionsResponse_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *ActionsResponse) GetExecute() *ExecuteRequest {
	if x != nil {
		if x, ok := x.Msg.(*ActionsResponse_Execute); ok {
			return x.Execute
		}
	}
	return nil
}

func (x *ActionsResponse) GetStatus() *StatusRequest {
	if x != nil {
		if x, ok := x.Msg.(*ActionsResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ActionsResponse) GetSchema() *SchemaRequest {
	if x != nil {
		if x, ok := x.Msg.(*ActionsResponse_Schema); ok {
			return x.Schema
		}
	}
	return nil
}

type isActionsResponse_Msg interface {
	isActionsResponse_Msg()
}

type ActionsResponse_List struct {
	List *ListRequest `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

type ActionsResponse_Execute struct {
	Execute *ExecuteRequest `protobuf:"bytes,4,opt,name=execute,proto3,oneof"`
}

type ActionsResponse_Status struct {
	Status *StatusRequest `protobuf:"bytes,5,opt,name=status,proto3,oneof"`
}

type ActionsResponse_Schema struct {
	Schema *SchemaRequest `protobuf:"bytes,6,opt,name=schema,proto3,oneof"`
}

func (*ActionsResponse_List) isActionsResponse_Msg() {}

func (*ActionsResponse_Execute) isActionsResponse_Msg() {}

func (*ActionsResponse_Status) isActionsResponse_Msg() {}

func (*ActionsResponse_Schema) isActionsResponse_Msg() {}

var File_zeloscloud_actions_actions_proto protoreflect.FileDescriptor

const file_zeloscloud_actions_actions_proto_rawDesc = "" +
	"\n" +
	" zeloscloud/actions/actions.proto\x12\x12zeloscloud.actions\"s\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06params\x18\x02 \x01(\tR\x06params\x12\"\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rH\x00R\ttimeoutMs\x88\x01\x01B\r\n" +
	"\v_timeout_ms\"\x8c\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2!.zeloscloud.actions.ExecuteStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\r\n" +
	"\vListRequest\"(\n" +
	"\fListResponse\x12\x18\n" +
	"\aactions\x18\x01 \x03(\tR\aactions\"\x0f\n" +
	"\rStatusRequest\"$\n" +
	"\x0eStatusResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"N\n" +
	"\rSchemaRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12%\n" +
	"\x0ecurrent_values\x18\x02 \x01(\tR\rcurrentValues\"\xb4\x01\n" +
	"\x0eSchemaResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12#\n" +
	"\raction_schema\x18\x02 \x01(\tR\factionSchema\x12\x1b\n" +
	"\tui_schema\x18\x03 \x01(\tR\buiSchema\x121\n" +
	"\x12default_timeout_ms\x18\x04 \x01(\rH\x00R\x10defaultTimeoutMs\x88\x01\x01B\x15\n" +
	"\x13_default_timeout_ms\"\xc9\x02\n" +
	"\x0eActionsRequest\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04R\x0esequenceNumber\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x04list\x18\x03 \x01(\v2 .zeloscloud.actions.ListResponseH\x00R\x04list\x12?\n" +
	"\aexecute\x18\x04 \x01(\v2#.zeloscloud.actions.ExecuteResponseH\x00R\aexecute\x12<\n" +
	"\x06status\x18\x05 \x01(\v2\".zeloscloud.actions.StatusResponseH\x00R\x06status\x12<\n" +
	"\x06schema\x18\x06 \x01(\v2\".zeloscloud.actions.SchemaResponseH\x00R\x06schemaB\x05\n" +
	"\x03msg\"\xb2\x02\n" +
	"\x0fActionsResponse\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04R\x0esequenceNumber\x125\n" +
	"\x04list\x18\x03 \x01(\v2\x1f.zeloscloud.actions.ListRequestH\x00R\x04list\x12>\n" +
	"\aexecute\x18\x04 \x01(\v2\".zeloscloud.actions.ExecuteRequestH\x00R\aexecute\x12;\n" +
	"\x06status\x18\x05 \x01(\v2!.zeloscloud.actions.StatusRequestH\x00R\x06status\x12;\n" +
	"\x06schema\x18\x06 \x01(\v2!.zeloscloud.actions.SchemaRequestH\x00R\x06schemaB\x05\n" +
	"\x03msg*8\n" +
	"\rExecuteStatus\x12\b\n" +
	"\x04PASS\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\b\n" +
	"\x04DONE\x10\x032\xd1\x02\n" +
	"\aActions\x12R\n" +
	"\aExecute\x12\".zeloscloud.actions.ExecuteRequest\x1a#.zeloscloud.actions.ExecuteResponse\x12I\n" +
	"\x04List\x12\x1f.zeloscloud.actions.ListRequest\x1a .zeloscloud.actions.ListResponse\x12O\n" +
	"\x06Schema\x12!.zeloscloud.actions.SchemaRequest\x1a\".zeloscloud.actions.SchemaResponse\x12V\n" +
	"\aActions\x12\".zeloscloud.actions.ActionsRequest\x1a#.zeloscloud.actions.ActionsResponse(\x010\x01b\x06proto3"

var (
	file_zeloscloud_actions_actions_proto_rawDescOnce sync.Once
	file_zeloscloud_actions_actions_proto_rawDescData []byte
)

func file_zeloscloud_actions_actions_proto_rawDescGZIP() []byte {
	file_zeloscloud_actions_actions_proto_rawDescOnce.Do(func() {
		file_zeloscloud_actions_actions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zeloscloud_actions_actions_proto_rawDesc), len(file_zeloscloud_actions_actions_proto_rawDesc)))
	})
	return file_zeloscloud_actions_actions_proto_rawDescData
}

var file_zeloscloud_actions_actions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zeloscloud_actions_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_zeloscloud_actions_actions_proto_goTypes = []any{
	(ExecuteStatus)(0),      // 0: zeloscloud.actions.ExecuteStatus
	(*ExecuteRequest)(nil),  // 1: zeloscloud.actions.ExecuteRequest
	(*ExecuteResponse)(nil), // 2: zeloscloud.actions.ExecuteResponse
	(*ListRequest)(nil),     // 3: zeloscloud.actions.ListRequest
	(*ListResponse)(nil),    // 4: zeloscloud.actions.ListResponse
	(*StatusRequest)(nil),   // 5: zeloscloud.actions.StatusRequest
	(*StatusResponse)(nil),  // 6: zeloscloud.actions.StatusResponse
	(*SchemaRequest)(nil),   // 7: zeloscloud.actions.SchemaRequest
	(*SchemaResponse)(nil),  // 8: zeloscloud.actions.SchemaResponse
	(*ActionsRequest)(nil),  // 9: zeloscloud.actions.ActionsRequest
	(*ActionsResponse)(nil), // 10: zeloscloud.actions.ActionsResponse
}
var file_zeloscloud_actions_actions_proto_depIdxs = []int32{
	0,  // 0: zeloscloud.actions.ExecuteResponse.status:type_name -> zeloscloud.actions.ExecuteStatus
	4,  // 1: zeloscloud.actions.ActionsRequest.list:type_name -> zeloscloud.actions.ListResponse
	2,  // 2: zeloscloud.actions.ActionsRequest.execute:type_name -> zeloscloud.actions.ExecuteResponse
	6,  // 3: zeloscloud.actions.ActionsRequest.status:type_name -> zeloscloud.actions.StatusResponse
	8,  // 4: zeloscloud.actions.ActionsRequest.schema:type_name -> zeloscloud.actions.SchemaResponse
	3,  // 5: zeloscloud.actions.ActionsResponse.list:type_name -> zeloscloud.actions.ListRequest
	1,  // 6: zeloscloud.actions.ActionsResponse.execute:type_name -> zeloscloud.actions.ExecuteRequest
	5,  // 7: zeloscloud.actions.ActionsResponse.status:type_name -> zeloscloud.actions.StatusRequest
	7,  // 8: zeloscloud.actions.ActionsResponse.schema:type_name -> zeloscloud.actions.SchemaRequest
	1,  // 9: zeloscloud.actions.Actions.Execute:input_type -> zeloscloud.actions.ExecuteRequest
	3,  // 10: zeloscloud.actions.Actions.List:input_type -> zeloscloud.actions.ListRequest
	7,  // 11: zeloscloud.actions.Actions.Schema:input_type -> zeloscloud.actions.SchemaRequest
	9,  // 12: zeloscloud.actions.Actions.Actions:input_type -> zeloscloud.actions.ActionsRequest
	2,  // 13: zeloscloud.actions.Actions.Execute:output_type -> zeloscloud.actions.ExecuteResponse
	4,  // 14: zeloscloud.actions.Actions.List:output_type -> zeloscloud.actions.ListResponse
	8,  // 15: zeloscloud.actions.Actions.Schema:output_type -> zeloscloud.actions.SchemaResponse
	10, // 16: zeloscloud.actions.Actions.Actions:output_type -> zeloscloud.actions.ActionsResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_zeloscloud_actions_actions_proto_init() }
func file_zeloscloud_actions_actions_proto_init() {
	if File_zeloscloud_actions_actions_proto != nil {
		return
	}
	file_zeloscloud_actions_actions_proto_msgTypes[0].OneofWrappers = []any{}
	file_zeloscloud_actions_actions_proto_msgTypes[1].OneofWrappers = []any{}
	file_zeloscloud_actions_actions_proto_msgTypes[7].OneofWrappers = []any{}
	file_zeloscloud_actions_actions_proto_msgTypes[8].OneofWrappers = []any{
		(*ActionsRequest_List)(nil),
		(*ActionsRequest_Execute)(nil),
		(*ActionsRequest_Status)(nil),
		(*ActionsRequest_Schema)(nil),
	}
	file_zeloscloud_actions_actions_proto_msgTypes[9].OneofWrappers = []any{
		(*ActionsResponse_List)(nil),
		(*ActionsResponse_Execute)(nil),
		(*ActionsResponse_Status)(nil),
		(*ActionsResponse_Schema)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zeloscloud_actions_actions_proto_rawDesc), len(file_zeloscloud_actions_actions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zeloscloud_actions_actions_proto_goTypes,
		DependencyIndexes: file_zeloscloud_actions_actions_proto_depIdxs,
		EnumInfos:         file_zeloscloud_actions_actions_proto_enumTypes,
		MessageInfos:      file_zeloscloud_actions_actions_proto_msgTypes,
	}.Build()
	File_zeloscloud_actions_actions_proto = out.File
	file_zeloscloud_actions_actions_proto_goTypes = nil
	file_zeloscloud_actions_actions_proto_depIdxs = nil
}
