// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: zeloscloud/trace/publish.proto

package trace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceMessages []*TraceMessage        `protobuf:"bytes,1,rep,name=trace_messages,json=traceMessages,proto3" json:"trace_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_zeloscloud_trace_publish_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_trace_publish_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_zeloscloud_trace_publish_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTraceMessages() []*TraceMessage {
	if x != nil {
		return x.TraceMessages
	}
	return nil
}

type PublishStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalMessages      uint64                 `protobuf:"varint,1,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	SuccessfulMessages uint64                 `protobuf:"varint,2,opt,name=successful_messages,json=successfulMessages,proto3" json:"successful_messages,omitempty"`
	FailedMessages     uint64                 `protobuf:"varint,3,opt,name=failed_messages,json=failedMessages,proto3" json:"failed_messages,omitempty"`
	LastError          string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PublishStatus) Reset() {
	*x = PublishStatus{}
	mi := &file_zeloscloud_trace_publish_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStatus) ProtoMessage() {}

func (x *PublishStatus) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_trace_publish_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStatus.ProtoReflect.Descriptor instead.
func (*PublishStatus) Descriptor() ([]byte, []int) {
	return file_zeloscloud_trace_publish_proto_rawDescGZIP(), []int{1}
}

func (x *PublishStatus) GetTotalMessages() uint64 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *PublishStatus) GetSuccessfulMessages() uint64 {
	if x != nil {
		return x.SuccessfulMessages
	}
	return 0
}

func (x *PublishStatus) GetFailedMessages() uint64 {
	if x != nil {
		return x.FailedMessages
	}
	return 0
}

func (x *PublishStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *PublishStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_zeloscloud_trace_publish_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zeloscloud_trace_publish_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_zeloscloud_trace_publish_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResponse) GetStatus() *PublishStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_zeloscloud_trace_publish_proto protoreflect.FileDescriptor

const file_zeloscloud_trace_publish_proto_rawDesc = "" +
	"\n" +
	"\x1ezeloscloud/trace/publish.proto\x12\x10zeloscloud.trace\x1a\x1czeloscloud/trace/trace.proto\"W\n" +
	"\x0ePublishRequest\x12E\n" +
	"\x0etrace_messages\x18\x01 \x03(\v2\x1e.zeloscloud.trace.TraceMessageR\rtraceMessages\"\xaf\x01\n" +
	"\rPublishStatus\x12%\n" +
	"\x0etotal_messages\x18\x01 \x01(\x04R\rtotalMessages\x12/\n" +
	"\x13successful_messages\x18\x02 \x01(\x04R\x12successfulMessages\x12'\n" +
	"\x0ffailed_messages\x18\x03 \x01(\x04R\x0efailedMessages\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"J\n" +
	"\x0fPublishResponse\x127\n" +
	"\x06status\x18\x01 \x01(\v2\x1f.zeloscloud.trace.PublishStatusR\x06status2b\n" +
	"\fTracePublish\x12R\n" +
	"\aPublish\x12 .zeloscloud.trace.PublishRequest\x1a!.zeloscloud.trace.PublishResponse(\x010\x01b\x06proto3"

var (
	file_zeloscloud_trace_publish_proto_rawDescOnce sync.Once
	file_zeloscloud_trace_publish_proto_rawDescData []byte
)

func file_zeloscloud_trace_publish_proto_rawDescGZIP() []byte {
	file_zeloscloud_trace_publish_proto_rawDescOnce.Do(func() {
		file_zeloscloud_trace_publish_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zeloscloud_trace_publish_proto_rawDesc), len(file_zeloscloud_trace_publish_proto_rawDesc)))
	})
	return file_zeloscloud_trace_publish_proto_rawDescData
}

var file_zeloscloud_trace_publish_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zeloscloud_trace_publish_proto_goTypes = []any{
	(*PublishRequest)(nil),  // 0: zeloscloud.trace.PublishRequest
	(*PublishStatus)(nil),   // 1: zeloscloud.trace.PublishStatus
	(*PublishResponse)(nil), // 2: zeloscloud.trace.PublishResponse
	(*TraceMessage)(nil),    // 3: zeloscloud.trace.TraceMessage
}
var file_zeloscloud_trace_publish_proto_depIdxs = []int32{
	3, // 0: zeloscloud.trace.PublishRequest.trace_messages:type_name -> zeloscloud.trace.TraceMessage
	1, // 1: zeloscloud.trace.PublishResponse.status:type_name -> zeloscloud.trace.PublishStatus
	0, // 2: zeloscloud.trace.TracePublish.Publish:input_type -> zeloscloud.trace.PublishRequest
	2, // 3: zeloscloud.trace.TracePublish.Publish:output_type -> zeloscloud.trace.PublishResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zeloscloud_trace_publish_proto_init() }
func file_zeloscloud_trace_publish_proto_init() {
	if File_zeloscloud_trace_publish_proto != nil {
		return
	}
	file_zeloscloud_trace_trace_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zeloscloud_trace_publish_proto_rawDesc), len(file_zeloscloud_trace_publish_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zeloscloud_trace_publish_proto_goTypes,
		DependencyIndexes: file_zeloscloud_trace_publish_proto_depIdxs,
		MessageInfos:      file_zeloscloud_trace_publish_proto_msgTypes,
	}.Build()
	File_zeloscloud_trace_publish_proto = out.File
	file_zeloscloud_trace_publish_proto_goTypes = nil
	file_zeloscloud_trace_publish_proto_depIdxs = nil
}
