// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: zeloscloud/trace/publish.proto

package trace

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TracePublish_Publish_FullMethodName = "/zeloscloud.trace.TracePublish/Publish"
)

// TracePublishClient is the client API for TracePublish service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TracePublishClient interface {
	Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRequest, PublishResponse], error)
}

type tracePublishClient struct {
	cc grpc.ClientConnInterface
}

func NewTracePublishClient(cc grpc.ClientConnInterface) TracePublishClient {
	return &tracePublishClient{cc}
}

func (c *tracePublishClient) Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRequest, PublishResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TracePublish_ServiceDesc.Streams[0], TracePublish_Publish_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishRequest, PublishResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TracePublish_PublishClient = grpc.BidiStreamingClient[PublishRequest, PublishResponse]

// TracePublishServer is the server API for TracePublish service.
// All implementations must embed UnimplementedTracePublishServer
// for forward compatibility.
type TracePublishServer interface {
	Publish(grpc.BidiStreamingServer[PublishRequest, PublishResponse]) error
	mustEmbedUnimplementedTracePublishServer()
}

// UnimplementedTracePublishServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTracePublishServer struct{}

func (UnimplementedTracePublishServer) Publish(grpc.BidiStreamingServer[PublishRequest, PublishResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedTracePublishServer) mustEmbedUnimplementedTracePublishServer() {}
func (UnimplementedTracePublishServer) testEmbeddedByValue()                      {}

// UnsafeTracePublishServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TracePublishServer will
// result in compilation errors.
type UnsafeTracePublishServer interface {
	mustEmbedUnimplementedTracePublishServer()
}

func RegisterTracePublishServer(s grpc.ServiceRegistrar, srv TracePublishServer) {
	// If the following call pancis, it indicates UnimplementedTracePublishServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TracePublish_ServiceDesc, srv)
}

func _TracePublish_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TracePublishServer).Publish(&grpc.GenericServerStream[PublishRequest, PublishResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TracePublish_PublishServer = grpc.BidiStreamingServer[PublishRequest, PublishResponse]

// TracePublish_ServiceDesc is the grpc.ServiceDesc for TracePublish service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TracePublish_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zeloscloud.trace.TracePublish",
	HandlerType: (*TracePublishServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _TracePublish_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "zeloscloud/trace/publish.proto",
}
